version: '3.8'
services:
  postgres_strapi:
    image: postgres:alpine
    container_name: postgres -> postgres-shop
    volumes:
      - ./.docker/postgres:/data/db
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
  redis:
    image: redis:alpine
    container_name: redis-shop
    volumes:
      - ./.docker/redis:/redis
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_DEFAULT_REGION=${S3_REGION}
      - EDGE_PORT=${S3_EDGE_PORT}
      - SERVICES=s3
    ports:
      - '${S3_PORT}:${S3_PORT}'
    volumes:
      - '${TEMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - ./aws:/docker-entrypoint-initaws.d
